# Generated by Django 2.1 on 2019-10-05 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='publish_date')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='publish_date')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.Rank')),
            ],
        ),
    ]
