# Generated by Django 2.1 on 2019-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='state',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='rank',
            name='submission',
            field=models.IntegerField(default=0),
        ),
    ]
