# Generated by Django 2.1 on 2019-10-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20191015_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='abstract',
            field=models.TextField(),
        ),
    ]
