# Generated by Django 2.1 on 2019-10-15 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_auto_20191015_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
